eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8070

spring:
  application:
    name: school
  config:
    import: optional:configserver:http://localhost:8888
    #students-url : http://localhost:8090/api/v1/students
    students-url: "http://localhost:8090/api/v1/students"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schools
    username: postgres
    password: 07197697

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
